# Generated by Django 3.2.6 on 2021-08-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('code', models.CharField(max_length=255, verbose_name='Code')),
                ('description', models.TextField(help_text='Description')),
                ('price', models.CharField(max_length=255, verbose_name='Price')),
            ],
        ),
    ]
