# https://towardsdatascience.com/how-to-run-postgresql-and-pgadmin-using-docker-3a6a8ae918b5
# https://docs.docker.com/samples/django/
# https://stackoverflow.com/questions/3855127/find-and-kill-process-locking-port-3000-on-mac

version: "3.9"
   
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  web:
    restart: always
    build: .
    volumes:
      - .:/code
      - static:/static
      - media:/media
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  
volumes:
  static:
  media:
