# Generated by Django 3.2.6 on 2021-08-26 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('source_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('starting_place', models.CharField(max_length=255)),
                ('ending_place', models.CharField(max_length=255)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Map History',
                'verbose_name_plural': 'Map Historys',
                'db_table': 'map_history',
            },
        ),
    ]
