# Generated by Django 3.2.6 on 2021-08-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_skill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maphistory',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
